[server]
headless = true
address = "0.0.0.0"
port = 8501
#port = 8501 for hosting on streamlit community cloud
#port = 5000 for local development

[theme]
primaryColor = "#0066cc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[client]
showSidebarNavigation = false
